version: '3.9'

services:
  app:
    build: .
    container_name: auth-node-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_started
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
